config/routes.rb
  Rails.application.routes.draw do
  # get 'users/show'


  mount Attachinary::Engine => "/attachinary"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  get 'search', to: 'pages#search'

  resources :users, only: [:show, :edit, :update] do
    resources :bookings
    resources :reviews, only: [:index, :show, :edit, :new, :create]
  end
end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :reviews, dependent: :destroy
  belongs_to :cleaner, class_name: 'User', foreign_key: 'cleaner_id'
  belongs_to :customer, class_name: 'User', foreign_key: 'customer_id'
  validates :cleaner_id, presence: true
  validates :customer_id, presence: true
  validates :date, presence: true
 # validates :status, presence: true
  # validates :payment_method, presence: true

  def total_price
    hrs_work*cleaner.hourly_rate
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :testimonial, presence: true
  validates :rating, presence: true, inclusion: { in: (0..5), allow_nil: false }, numericality: { only_integer: true }

  def blank_stars
   5 - rating.to_i
 end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attachment :photo

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :reviews
  geocoded_by :address
  validates :address, presence: true
  after_validation :geocode, if: :address_changed?

  geocoded_by :address

   def self.find_for_facebook_oauth(data)
      email = data.info.email
      uid = data.uid

      user = User.where(email: email, uid: uid).first

      if user.nil?
          User.create({
            provider: "facebook",
            uid: uid,
            first_name: data.info.first_name,
            last_name: data.info.last_name,
            email: email,
            facebook_picture_url: data.info.image,
            password: Devise.friendly_token[0,20]
          })
      else
          user
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo, :role_cleaner])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  #/bookings
  #/cleaners/1/bookings
  def index
    # Lists all the users booking
    if current_user.role_cleaner == true
      @bookings = Booking.where(cleaner_id: current_user.id)
    else
      @bookings = Booking.where(customer_id: current_user.id)
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.customer = current_user
    @booking.cleaner = User.find(params[:user_id])
    if @booking.save
      redirect_to user_booking_path(user_id:current_user.id, id:@booking.id)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    @booking = Booking.find(params[:id])
    if params[:status] == 'accepted'
      @booking.status = params[:status]
      @booking.save
    elsif params[:status] == 'declined'
      @booking.status = params[:status]
      @booking.save
    else params[:status] == 'pending'
    end
  end

  private

  def booking_params
   params.require(:booking).permit(:date, :message, :hrs_work, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @users = User.all
    @cleaners = User.near('Rua da Sociedade Farmaceutica Lisboa', 100)
    @hash = Gmaps4rails.build_markers(@cleaners) do |cleaner, marker|
      marker.lat cleaner.latitude
      marker.lng cleaner.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end
  def search
    # address = params[:address]
    address = params[:address]
    @cleaners = User.where(role_cleaner: true).near(address, 100)
    @hash = Gmaps4rails.build_markers(@cleaners) do |cleaner, marker|
      marker.lat cleaner.latitude
      marker.lng cleaner.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @user = User.find(params[:user_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
  	@user = User.find(params[:user_id])
    @review.user_id = @user.id
    if @review.save
      redirect_to user_path(@user)
    else
      render "new"
    end
  end

  def show
  	@review = Review.find(params[:id])
  end

  def edit
  	@review = Review.find(params[:id])
  end

private

  def review_params
    params.require(:review).permit(:testimonial, :rating)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])


    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = User.find(params[:id])
    @booking = Booking.new
    # @user_coordinates = { lat: @user.latitude, lng: @user.longitude }
    @hash = Gmaps4rails.build_markers(@user) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    @review = Review.new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
  end

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :photo, :address, :city, :location, :country, :postal_code, :latitude, :longitude, :phone_number)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container">
<div class="row">
          <div class="col-lg-8">
            <div class="box-simple">
              <div class="icon"><i class="pe-7s-like"></i></div>
              <div class="content">
                <h4>Book <%= User.find(params[:user_id]).first_name.capitalize%></h4>
                  <%= simple_form_for [@user, @booking] do |f| %>
                  <div class="row">
                    <div class="col-sm-6">
                      <div class="form-group">
                        <%= f.input :date, input_html: {id: "datepicker"}, placeholder: "Date", as: :string %>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="form-group">
                        <%= f.input :hrs_work, input_html: {class: "form-control"}, placeholder: "2" %>
                      </div>
                    </div>
                    <div class="col-sm-12">
                      <div class="form-group">
                        <%= f.input :address, input_html: {class: "form-control"}, placeholder: "2" %>
                      </div>
                    </div>
                    <div class="col-sm-12">
                      <div class="form-group">
                        <label for="message">Message</label>
                        <textarea id="message" class="form-control"></textarea>
                      </div>
                    </div>
                    <div class="col-sm-12">
                      <%= f.submit "Book", class: "btn btn-primary" %>
                    </div>
                  </div>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
</div>
</script>

app/views/bookings/index.html.erb
<div class="container">
  <section class="section--padding-bottom-small">
    <div class="container">
<% if current_user.role_cleaner? %>
<h1><i class="pe-7s-piggy"></i> Earnings</h1>
<h3>Hello <%= current_user.first_name %>, you have made earned: XXX € this month.</h3>
<% end %></div></section>


<section class="section--padding-bottom-small">
    <div class="container">
      <h2>Results</h2>
      <% @bookings.each do |booking| %>
      <% cleaner = User.find(booking.cleaner_id) %>
      <%= link_to user_booking_path(user_id: current_user.id, id: booking.id) do %>
      <div class="row">
        <div class="col-sm-4">
          <div class="post">
            <div class="image">
              <% avatar_url = cleaner.facebook_picture_url || (cleaner.photo? ? cl_image_path(cleaner.photo.path, :crop => "fill") : "http://via.placeholder.com/350x150") %>
              <%= cl_image_tag avatar_url, class: "avatar img-responsive" %>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
          <div class="post" style="text-align:left">
            <h3><%= cleaner.first_name%></h3>
            <ul>
              <li>Hourly rate: <%= cleaner.hourly_rate%></li>
              <li>Discount for aditional hours: 50%</li>
              <li>Rating: ***** </li>
              <li>Received at: <%= booking.created_at%> </li>
            </ul>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="post" style="text-align:center">Services</div>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </section>
</div>

app/views/bookings/new.html.erb
<%= render "form" %>

app/views/bookings/show.html.erb
<h2>Booking with <%= User.find(@booking.cleaner_id).first_name %></h2>

<div class="cleaner-view">
<% if current_user.role_cleaner%>
  <p>When: <%= @booking.date %> for <%= @booking.hrs_work %> hours</p>
  <p>Salary: <%= @booking.total_price %> $ </p>
  <p> Message: <%= @booking.message %></p>
  <%= form_for @booking do |f| %>
    <%= f.button "Accept", name: "status", value: "accepted", class: "btn btn-success" %>
    <%= f.button "Decline", name: "status", value: "declined", class: "btn btn-danger" %>
  <% end %>
  </div>
  <% else %>
  <p>Booking details: <%= @booking.date %> for <%= @booking.hrs_work %> hours </p>
  <p>Amount to pay: <%= @booking.total_price %> $ </p>
  <p>Address: <%= @booking.address %> </p>
  <p>Status of booking: <%= @booking.status %> </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Easy Cleaners - Find cleaning professionals near to you</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="favicon.png">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body class="home">
    <!-- navbar-->
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <!-- *** LOGIN MODAL ***_________________________________________________________-->

    <!-- *** LOGIN MODAL END ***-->
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag "application" %>
    <%= yield(:after_js) %>
    <%= cloudinary_js_config %>
    <!-- Javascript files-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div id="carousel-home" data-ride="carousel" class="carousel slide carousel-fullscreen carousel-fade">
  <!-- Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-home" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-home" data-slide-to="1"></li>
    <li data-target="#carousel-home" data-slide-to="2"></li>
  </ol>
  <!-- Wrapper for slides-->
  <div role="listbox" class="carousel-inner">
    <div style="background-image: url('<%= image_path "cleaners.jpg" %>');" class="item active">
      <div class="overlay"></div>
      <div class="carousel-caption">
        <h1 class="super-heading">Easy Cleaners</h1>
        <p class="super-paragraph">Find home cleaning professionals near you</p>
        </div>
      </div>
      <div style="background-image: url('<%= image_path "cleaners.jpg" %>');" class="item">
        <div class="overlay"></div>
        <div class="carousel-caption">
          <h1 class="super-heading">Easy Cleaners</h1>
          <p class="super-paragraph">Find home cleaning professionals near you</p>
          </div>
        </div>
        <div style="background-image: url('<%= image_path "cleaners.jpg" %>');" class="item">
          <div class="overlay"></div>
          <div class="carousel-caption">
            <h1 class="super-heading">Easy Cleaners</h1>
            <p class="super-paragraph">Find home cleaning professionals near you</p>
            </div>
          </div>
        </div>
      </div>
      <section class="background-gray-lightest">
        <div class="container">
          <h1> Cleaning professionals near you</h1>
        </div>
        <div id="map" style="width: 100%; height: 350px;"></div>
                <% content_for(:after_js) do %>
                    <%= javascript_tag do %>
                    var handler = Gmaps.build('Google');
                    handler.buildMap({ internal: { id: 'map' } }, function() {
                    markers = handler.addMarkers(<%= raw @hash.to_json %>);
                    handler.bounds.extendWith(markers);
                    handler.fitMapToBounds();
                    if (markers.length == 0) {
                    handler.getMap().setZoom(2);
                  } else if (markers.length == 1) {
                  handler.getMap().setZoom(14);
                }
              });
              <% end %>
          <% end %>
      </section>
<section class="section--padding-bottom-small">
  <div class="container">
    <h2>How does it work?</h2>
      <div class="row">
        <div class="col-sm-4">
          <div class="post">
            <div class="image"><a href="text.html">
              <%= image_tag "step1.png", class: "img-responsive"  %></a>
            </div>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="post">
              <div class="image"><a href="text.html">
                <%= image_tag "step2.png", class: "img-responsive"  %></a>
              </div>
            </div>
            </div>
            <div class="col-sm-4">
              <div class="post">
                <div class="image"><a href="text.html">
                  <%= image_tag "step3.png", class: "img-responsive"  %></a>
                </div>
              </div>
              </div>
            </div>
          </div>
        </section>
    </div>
  </div>
</div>

app/views/pages/search.html.erb
<section class="background-gray-lightest">
  <div class="container">
    <h1>Search</h1>

    <form>
     <div class="row">
       <div class="col-sm-12">
         <div class="form-group">
           <input id="address" name="address" type="text" class="form-control" placeholder="Enter your location, address, reference "></div>
         </div>
       </div>
     </form>
     <div id="map" style="width: 100%; height: 350px;"></div>
     <% content_for(:after_js) do %>
     <%= javascript_tag do %>
       var handler = Gmaps.build('Google');
       handler.buildMap({ internal: { id: 'map' } }, function() {
       markers = handler.addMarkers(<%= raw @hash.to_json %>);
       handler.bounds.extendWith(markers);
       handler.fitMapToBounds();
       if (markers.length == 0) {
         handler.getMap().setZoom(2);
       } else if (markers.length == 1) {
       handler.getMap().setZoom(14);
        }
      });
      <% end %>
    <% end %>
  </div>
  <section class="section--padding-bottom-small">
    <div class="container">
      <h2>Results</h2>
      <% @cleaners.each do |cleaner| %>
      <%= link_to user_path(id: cleaner.id) do %>
      <div class="row">
        <div class="col-sm-4">
          <div class="post">
            <div class="image">
              <% avatar_url = cleaner.facebook_picture_url || (cleaner.photo? ? cl_image_path(cleaner.photo.path, :crop => "fill") : "http://via.placeholder.com/350x150") %>
              <%= cl_image_tag avatar_url, class: "avatar img-responsive" %>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
          <div class="post" style="text-align:left">
            <h3><%= cleaner.first_name%></h3>
            <ul>
              <li>Hourly rate: <%= cleaner.hourly_rate%></li>
              <li>Discount for aditional hours: 50%</li>
              <li>Rating: ***** </li>
            </ul>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="post" style="text-align:center">Services</div>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </section>
  </div>
</section>

app/views/reviews/_form.html.erb
<section class="background-gray-lightest">

  <div class="container clearfix">
  <div class="header"><h4>Please add a review for <%= @user.first_name %> <%= @user.last_name %></h4>
  </div>
    <%= simple_form_for [@user, @review] do |f| %>
    <div class="testimonial-input"> <%= f.input :testimonial %></div>
    <div class="rating-input">
      <%= f.input :rating, collection: [0,1,2,3,4,5] %> </div>
      <%= f.button :submit, class: "btn btn-ghost" %>
      <% end %>
    </div>
  </section>

app/views/reviews/_review_index.erb
<div class="message">
 <% avatar_url = current_user.facebook_picture_url || (current_user.photo? ? cl_image_path( current_user.photo.path, :crop => "fill") : "http://via.placeholder.com/350x150") %>
 <div class="message-name">
 </div>
 <div class="message-body">
  <% @review.rating.to_i.times do  %>
  <span class="glyphicon glyphicon-star"></span>
  <% end %>
  <p>
   <%= @review.testimonial %>
 </p>
</div>
</div>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<%= render 'form' %>

app/views/reviews/show.html.erb
<p>Review</p>

<%= render "review_index" %>

app/views/shared/_flashes.html.erb
<div class="container">
<% if notice %>
  <div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer__copyright">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>&copy;2017 Easy Cleaners</p>
        </div>
        <div class="col-md-6">
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_loginmodal.html.erb
<div id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true" class="modal fade">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" data-dismiss="modal" aria-hidden="true" class="close">×</button>
            <h4 id="Login" class="modal-title">Customer login</h4>
          </div>
          <div class="modal-body">
            <form action="customer-orders.html" method="post">
              <div class="form-group">
                <input id="email_modal" type="text" placeholder="email" class="form-control">
              </div>
              <div class="form-group">
                <input id="password_modal" type="password" placeholder="password" class="form-control">
              </div>
              <p class="text-center">
                <button type="button" class="btn btn-primary"><i class="fa fa-sign-in"></i> Log in</button>
              </p>
            </form>
            <p class="text-center text-muted">Not registered yet?</p>
            <p class="text-center text-muted"><a href="#"><strong>Register now</strong></a>! It is easy and done in 1 minute and gives you access to special discounts and much more!</p>
          </div>
        </div>
      </div>
    </div>

app/views/shared/_navbar.html.erb
<header class="header">
  <div role="navigation" class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Easy Cleaners", root_path, class: "navbar-brand"%>
        <div class="navbar-buttons">
          <button type="button" data-toggle="collapse" data-target=".navbar-collapse" class="navbar-toggle navbar-btn">Menu<i class="fa fa-align-justify"></i></button>
        </div>
      </div>
      <div id="navigation" class="collapse navbar-collapse navbar-right">
        <ul class="nav navbar-nav">
           <% if user_signed_in? %>
           <!-- Links when logged in -->
            <li class="active"><%= link_to "Home", root_path %></li>
            <li><%= link_to "Search", search_path %></li>
            <li><%= link_to "My Bookings", user_bookings_path(user_id: current_user.id) %></li>
            <li class="dropdown">
              <% avatar_url = current_user.facebook_picture_url || (current_user.photo? ? cl_image_path( current_user.photo.path, :crop => "fill") : "http://via.placeholder.com/350x150") %>
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                <%= image_tag avatar_url, class: "avatar-sm" %>
              </a>
              <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(id: current_user.id) %></li>
              <li><%= link_to "Account", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></a></li>
              </ul>
            </li>
          </ul>
          <% else %>
          <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "btn navbar-btn btn-ghost" %>

          <% end %>
        </div>
      </div>
    </div>
  </header>